FROM alpine:3.23

RUN apk add --no-cache \
    ca-certificates \
    helm \
    kubectl \
    && addgroup -S lfk \
    && adduser -S lfk -G lfk

COPY lfk /usr/local/bin/lfk

ENV TERM=xterm-256color
ENV COLORTERM=truecolor

USER lfk

ENTRYPOINT ["lfk"]
